/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.jinternalframe.calculator;

import control.Calculate;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author italo
 */
public class SimpleCalculatorAA extends javax.swing.JInternalFrame {

    private final Calculate CALC = new Calculate();
    private double valorUm;
    private boolean operacaoInvalida = false;

    /**
     * Creates new form JInternalFrameSimpleCalculator
     */
    public SimpleCalculatorAA() {
        initComponents();
    }

    private void novaAcao() {
        if (contemNumeros(jtfValorUm.getText())) {
            JOptionPane.showMessageDialog(this, "Operacao invalida");
        } else {
            System.out.println("aa");
        }
    }
    
    private boolean contemNumeros(String string) {
        return string.matches("[0-9]");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtfValorUm = new javax.swing.JTextField();
        jtfValorDois = new javax.swing.JTextField();
        jtfOperacao = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Simple calculate");

        jtfValorUm.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jtfValorUm.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtfValorUm.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, new java.awt.Color(0, 0, 0)));
        jtfValorUm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfValorUmKeyTyped(evt);
            }
        });

        jtfValorDois.setEditable(false);
        jtfValorDois.setBackground(new java.awt.Color(255, 255, 255));
        jtfValorDois.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtfValorDois.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 0, 0, new java.awt.Color(0, 0, 0)));

        jtfOperacao.setEditable(false);
        jtfOperacao.setBackground(new java.awt.Color(255, 255, 255));
        jtfOperacao.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtfOperacao.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 1, new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Pressione enter para confirmar uma ação");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfValorUm)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtfValorDois, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtfOperacao, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfValorDois, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfOperacao, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfValorUm, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfValorUmKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfValorUmKeyTyped
        // TODO add your handling code here:
        if (!(evt.getKeyChar() + "").matches("[0-9/*\\-+,.]")) {
            evt.consume();
        } else if (evt.getKeyChar() == ',') {
            evt.setKeyChar('.');
        }
        
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            novaAcao();
        }
    }//GEN-LAST:event_jtfValorUmKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jtfOperacao;
    private javax.swing.JTextField jtfValorDois;
    private javax.swing.JTextField jtfValorUm;
    // End of variables declaration//GEN-END:variables
}
