/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.jinternalframe.convert;

import java.awt.event.KeyEvent;
import java.time.LocalDate;
import java.time.format.TextStyle;
import java.util.Locale;
import javax.swing.JOptionPane;

/**
 *
 * @author italo
 */
public class ConvertTime extends javax.swing.JInternalFrame {

    private int dataDay = 0;
    private int dataMonth = 0;
    private int dataYear = 0;
    
    /**
     * Creates new form ConvertTime
     */
    public ConvertTime() {
        initComponents();
    }
    
    private void adicionarAnos(int anos) {
        if (validarCampoData(jtfDataAdicionar.getText())) {
            dataYear += anos;
            atualizarDataAdicionar();
        } else {
            showMenssageError("Há alguma mensagem de erro no sistema");
        }
    }
    
    private void adicionarMeses(int meses) {
        dataMonth += meses;
        atualizarDataAdicionar();
    }
    
    private void adicionarDias(int dias) {
        dataDay = dataDay + dias;
        atualizarDataAdicionar();
    }
    
    private void atualizarDataAdicionar() {
        jtfDataAdicionar.setText(dataDay + "/" + dataMonth + "/" + dataYear);
    }
    
    private void calcularDataDiferenca() {
        if (validarFormatoData(jtfDataFinal.getText())) {
            clearMenssageError();
            
        } else {
            showMenssageError("Insira inicialmente uma data válida no formato xx/xx/xxxx");
        }
    }
    
    private void mostrarDiaDaSemana() {
        if (validarFormatoData(jtfDataDiaSemana.getText())) {
            clearMenssageError();
            
            String[] dataTela = jtfDataDiaSemana.getText().split("/");
            
            jlbDiaDaSemana.setText(LocalDate.of(Integer.parseInt(dataTela[2]),
                                                Integer.parseInt(dataTela[1]),
                                                Integer.parseInt(dataTela[0])).getDayOfWeek().getDisplayName(TextStyle.FULL, Locale.getDefault()).toLowerCase());
        } else {
            showMenssageError("O formato do campo é xx/xx/xxxx incluindo as barras");
        }
    }
    
    private boolean validarCampoData(String campo) {
        return true;
    }
    
    private boolean validarFormatoData(String string) {
        return string.matches("\\d\\d/\\d\\d/\\d\\d\\d\\d");
    }
    
    private void showMenssageError(String mensageError) {
        jlbError.setText(mensageError);
    }
    
    private void clearMenssageError() {
        jlbError.setText("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jtfMilessegundo = new javax.swing.JTextField();
        jtfSegundo = new javax.swing.JTextField();
        jtfMinuto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtfHora = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jtfDia = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jtfSemana = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jtfMes = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jtfAno = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jlbError = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jtfDataAdicionar = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jtfAcrescentarDia = new javax.swing.JTextField();
        jtfAcrescentarMes = new javax.swing.JTextField();
        jtfAcrescentarAno = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jtfDataDiaSemana = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jlbDiaDaSemana = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jtfDataInicial = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtfDataFinal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtfDataDiferenca = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Convert time");

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        jLabel3.setFont(new java.awt.Font("Arimo", 0, 14)); // NOI18N
        jLabel3.setText("Minuto:");

        jtfMilessegundo.setFont(new java.awt.Font("Arimo", 0, 14)); // NOI18N

        jtfSegundo.setFont(new java.awt.Font("Arimo", 0, 14)); // NOI18N

        jtfMinuto.setFont(new java.awt.Font("Arimo", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arimo", 0, 14)); // NOI18N
        jLabel1.setText("Milissegundo:");

        jLabel2.setFont(new java.awt.Font("Arimo", 0, 14)); // NOI18N
        jLabel2.setText("Segundo:");

        jLabel9.setFont(new java.awt.Font("Arimo", 0, 14)); // NOI18N
        jLabel9.setText("Hora:");

        jtfHora.setFont(new java.awt.Font("Arimo", 0, 14)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Arimo", 0, 14)); // NOI18N
        jLabel11.setText("Dia:");

        jtfDia.setFont(new java.awt.Font("Arimo", 0, 14)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Arimo", 0, 14)); // NOI18N
        jLabel12.setText("Semana:");

        jtfSemana.setFont(new java.awt.Font("Arimo", 0, 14)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Arimo", 0, 14)); // NOI18N
        jLabel13.setText("Mês");

        jtfMes.setFont(new java.awt.Font("Arimo", 0, 14)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Arimo", 0, 14)); // NOI18N
        jLabel14.setText("Ano");

        jtfAno.setFont(new java.awt.Font("Arimo", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jtfAno)
                    .addComponent(jtfMes)
                    .addComponent(jtfSemana)
                    .addComponent(jtfDia)
                    .addComponent(jtfHora)
                    .addComponent(jtfMinuto, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfSegundo, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfMilessegundo, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(162, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfMilessegundo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfSegundo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfMinuto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jtfHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jtfDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jtfSemana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jtfMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jtfAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(89, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Tempo", jPanel2);

        jLabel10.setText("- pressione enter no campo para realizar a ação");

        jlbError.setForeground(new java.awt.Color(204, 0, 0));

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jtfDataAdicionar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jtfDataAdicionar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfDataAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfDataAdicionarActionPerformed(evt);
            }
        });
        jtfDataAdicionar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfDataAdicionarKeyTyped(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel17.setText("Acrescenta...");

        jtfAcrescentarDia.setBorder(javax.swing.BorderFactory.createTitledBorder("Dia (s):"));
        jtfAcrescentarDia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfAcrescentarDiaKeyTyped(evt);
            }
        });

        jtfAcrescentarMes.setBorder(javax.swing.BorderFactory.createTitledBorder("Mês (es):"));
        jtfAcrescentarMes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfAcrescentarMesKeyTyped(evt);
            }
        });

        jtfAcrescentarAno.setBorder(javax.swing.BorderFactory.createTitledBorder("Ano (s)"));
        jtfAcrescentarAno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfAcrescentarAnoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfDataAdicionar)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jtfAcrescentarDia, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(jtfAcrescentarMes, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtfAcrescentarAno, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfAcrescentarDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfAcrescentarMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfAcrescentarAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfDataAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jtfDataDiaSemana.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jtfDataDiaSemana.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfDataDiaSemana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfDataDiaSemanaActionPerformed(evt);
            }
        });
        jtfDataDiaSemana.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfDataDiaSemanaKeyTyped(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel16.setText("Qual é o dia da semana?");

        jlbDiaDaSemana.setFont(new java.awt.Font("Arimo", 0, 14)); // NOI18N
        jlbDiaDaSemana.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 0, new java.awt.Color(0, 0, 0)));

        jLabel5.setFont(new java.awt.Font("Arimo", 0, 14)); // NOI18N
        jLabel5.setText("é (uma):");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jtfDataDiaSemana, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlbDiaDaSemana, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel16))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfDataDiaSemana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jlbDiaDaSemana, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jtfDataInicial.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jtfDataInicial.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfDataInicial.setText("12/04/2000");
        jtfDataInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfDataInicialActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arimo", 0, 14)); // NOI18N
        jLabel4.setText("Data final:");

        jtfDataFinal.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jtfDataFinal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfDataFinal.setText("12/04/2020");
        jtfDataFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfDataFinalActionPerformed(evt);
            }
        });
        jtfDataFinal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfDataFinalKeyTyped(evt);
            }
        });

        jLabel6.setText("=");

        jtfDataDiferenca.setEditable(false);
        jtfDataDiferenca.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jtfDataDiferenca.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfDataDiferenca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfDataDiferencaActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arimo", 0, 14)); // NOI18N
        jLabel7.setText("Diferença:");

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel15.setText("Calcula diferença entre datas:");

        jLabel8.setFont(new java.awt.Font("Arimo", 0, 14)); // NOI18N
        jLabel8.setText("Data inicial:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfDataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jtfDataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6))
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jtfDataDiferenca, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel15))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfDataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfDataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jtfDataDiferenca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlbError, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlbError, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Datas", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfDataInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfDataInicialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfDataInicialActionPerformed

    private void jtfDataFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfDataFinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfDataFinalActionPerformed

    private void jtfDataDiferencaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfDataDiferencaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfDataDiferencaActionPerformed

    private void jtfDataDiaSemanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfDataDiaSemanaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfDataDiaSemanaActionPerformed

    private void jtfDataDiaSemanaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfDataDiaSemanaKeyTyped
        // TODO add your handling code here:
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            mostrarDiaDaSemana();
        }
    }//GEN-LAST:event_jtfDataDiaSemanaKeyTyped

    private void jtfDataAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfDataAdicionarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfDataAdicionarActionPerformed

    private void jtfDataAdicionarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfDataAdicionarKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfDataAdicionarKeyTyped

    private void jtfDataFinalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfDataFinalKeyTyped
        // TODO add your handling code here:
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            calcularDataDiferenca();
        }
    }//GEN-LAST:event_jtfDataFinalKeyTyped

    private void jtfAcrescentarDiaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfAcrescentarDiaKeyTyped
        // TODO add your handling code here:
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
        }
    }//GEN-LAST:event_jtfAcrescentarDiaKeyTyped

    private void jtfAcrescentarMesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfAcrescentarMesKeyTyped
        // TODO add your handling code here:
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            
        }
    }//GEN-LAST:event_jtfAcrescentarMesKeyTyped

    private void jtfAcrescentarAnoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfAcrescentarAnoKeyTyped
        // TODO add your handling code here:
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            
        }
    }//GEN-LAST:event_jtfAcrescentarAnoKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel jlbDiaDaSemana;
    private javax.swing.JLabel jlbError;
    private javax.swing.JTextField jtfAcrescentarAno;
    private javax.swing.JTextField jtfAcrescentarDia;
    private javax.swing.JTextField jtfAcrescentarMes;
    private javax.swing.JTextField jtfAno;
    private javax.swing.JTextField jtfDataAdicionar;
    private javax.swing.JTextField jtfDataDiaSemana;
    private javax.swing.JTextField jtfDataDiferenca;
    private javax.swing.JTextField jtfDataFinal;
    private javax.swing.JTextField jtfDataInicial;
    private javax.swing.JTextField jtfDia;
    private javax.swing.JTextField jtfHora;
    private javax.swing.JTextField jtfMes;
    private javax.swing.JTextField jtfMilessegundo;
    private javax.swing.JTextField jtfMinuto;
    private javax.swing.JTextField jtfSegundo;
    private javax.swing.JTextField jtfSemana;
    // End of variables declaration//GEN-END:variables
}
